### ISSUE TITLE
Documentation or examples?

### ISSUE THREAD

**Issue by RowdyHowell** [bendoerr/airflow-mesos-executor#1]
I found this on the airflow gitter and am interested in using it for a project.  I think I understand how to use it, but wanted to know if there are still plans to build out the documentation?  Some examples of how you are using it would be helpful too.

**Comment by dlsuzuki** [comment]
This is also of great interest to me.  I am evaluating a migration from Chronos to Airflow for job graph processing on DC/OS, but we need to be able to use different CPU/mem reservations and different container images for each task.  I had thought about extending the contrib mesos_executor, but it looks like this one has already implemented some of the capabilities that we need.

**Comment by bendoerr** [comment]
Hey, missed the comments here. I'm really happy to add some documentation etc. I've also got a bunch of bug fixes on an internal repo that I'll push out. Give me a day or so.

**Comment by bendoerr** [comment]
We'll I clearly failed here. Unfortunately I don't work with Mesos anymore, so I'm going to close this.
